@url = http://localhost:4004/odata/v4/customers
@auth = Basic alice:alice

###
GET {{url}}/Customers
Authorization: {{auth}}

###
POST {{url}}/Customers
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "ACME Inc."
}

###
# @name CreateSecondCustomer
POST {{url}}/Customers
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "Foo Inc."
}

###
GET {{url}}/Customers(ID={{CreateSecondCustomer.response.body.ID}})
Authorization: {{auth}}

###
PUT {{url}}/Customers(ID={{CreateSecondCustomer.response.body.ID}})
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "Foo 2 Inc."
}

###
DELETE {{url}}/Customers(ID={{CreateSecondCustomer.response.body.ID}})
Authorization: {{auth}}

###
GET {{url}}/ProjectTypes
Authorization: {{auth}}

###
GET {{url}}/ProjectTypes
Authorization: {{auth}}
Accept-Language: de

###
GET {{url}}/Customers(ID=29514726-9142-4af7-96db-3221a4fb817b)?$expand=projects
Authorization: {{auth}}