@url = http://localhost:4004/odata/v4/projects
@auth = Basic alice:alice

###
GET {{url}}/isStarted(project=c8941700-2a5e-4cae-a809-70d43f647029)
Authorization: {{auth}}

###
POST {{url}}/endProject
Authorization: {{auth}}
Content-Type: application/json

{
    "project": "c8941700-2a5e-4cae-a809-70d43f647029"
}

###
GET {{url}}/Projects(ID=c8941700-2a5e-4cae-a809-70d43f647029,IsActiveEntity=true)/ProjectsService.hasStarted()
Authorization: {{auth}}

###
GET {{url}}/Projects(ID=c8941700-2a5e-4cae-a809-70d43f647029,IsActiveEntity=true)/ProjectsService.hasEnded()
Authorization: {{auth}}

###
POST {{url}}/Projects(ID=c8941700-2a5e-4cae-a809-70d43f647029,IsActiveEntity=true)/ProjectsService.stop
Authorization: {{auth}}
Content-Type: application/json

{
    "endDate": "2023-10-25"
}

###
GET {{url}}/Projects(ID=c8941700-2a5e-4cae-a809-70d43f647029,IsActiveEntity=true)
Authorization: {{auth}}

###
GET {{url}}/Projects
Authorization: {{auth}}

###
GET {{url}}/Projects(ID=c8941700-2a5e-4cae-a809-70d43f647029,IsActiveEntity=true)
Authorization: {{auth}}

###
PUT {{url}}/Projects(ID=c8941700-2a5e-4cae-a809-70d43f647029,IsActiveEntity=true)
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "My Fancy Project"
}

###
DELETE {{url}}/Projects(ID=011a74f1-fc58-4502-8797-3dddc78e69cd,IsActiveEntity=true)
Authorization: {{auth}}

###
POST {{url}}/Projects
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "My Fancy Project",
    "startDate": "2023-01-11"
}